site_name: Woningwaardering
site_author: Tomer Gabay, Ben Verhees, Tiddo Loos
copyright: "2025, Woonstad Rotterdam"
repo_url: https://github.com/woonstadrotterdam/woningwaardering

theme:
  name: material
  language: nl
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.scrollable
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


markdown_extensions:
  - github-callouts
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - include-markdown
  - autorefs

nav:
  - Introductie:
    - Overzicht: index.md
    - Opzet: introductie/opzet.md
  - Aan de slag:
    - Installatie: aan-de-slag/index.md
    - Gebruik: aan-de-slag/gebruik.md
    - Voorbeelden: aan-de-slag/voorbeelden.md
  - Implementatietoelichtingen:
    - Overzicht: implementatietoelichtingen/index.md
    - Zelfstandige woonruimten: implementatietoelichtingen/zelfstandige-woonruimten.md
    - Onzelfstandige woonruimten: implementatietoelichtingen/onzelfstandige-woonruimten.md
    - Datamodel Uitbreidingen: implementatietoelichtingen/datamodel-uitbreidingen.md
  - Voor ontwikkelaars:
    - Installatie: voor-ontwikkelaars/index.md
    - Naamgeving: voor-ontwikkelaars/naamgeving.md
    - Releasemanagement: voor-ontwikkelaars/releases.md
    - Testing: voor-ontwikkelaars/testing.md
    - Logger guidelines: voor-ontwikkelaars/logging.md
    - Data: voor-ontwikkelaars/data.md
 