site_name: Woningwaardering
site_author: Tomer Gabay, Ben Verhees, Tiddo Loos
copyright: "2025, Woonstad Rotterdam"

theme:
  name: readthedocs
  titles_only: false
  collapse_navigation: false
  include_homepage_in_sidebar: false

markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: true
  - github-callouts
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - include-markdown
  - autorefs

nav:
  - 🏠 Home: index.md
  - 📖 Introductie:
    - Overzicht: introductie/overzicht.md
    - Opzet Woningwaardering: introductie/opzet.md
  - 🚀 Aan de slag:
    - Installatie: aan-de-slag/installatie.md
    - Gebruik: aan-de-slag/gebruik.md
    - Voorbeelden: aan-de-slag/voorbeelden.md
  - 📚 Implementatietoelichtingen:
    - Zelfstandige woonruimten: implementatietoelichtingen/zelfstandige-woonruimten.md
    - Onzelfstandige woonruimten: implementatietoelichtingen/onzelfstandige-woonruimten.md
    - Datamodel Uitbreidingen: implementatietoelichtingen/datamodel-uitbreidingen.md
  - 👩‍💻 Voor Ontwikkelaars:
    - Bijdragen: voor-ontwikkelaars/index.md
  
 