version: "3"

tasks:
  genereer-vera-bvg-modellen:
    desc: Generate VERA BVG modellen
    cmds:
      - |
        datamodel-codegen \
          --url https://raw.githubusercontent.com/Aedes-datastandaarden/vera-openapi/main/docs/Ketenprocessen/BVG.yaml \
          --output woningwaardering/vera/bvg/generated.py \
          --output-model-type pydantic_v2.BaseModel \
          --use-standard-collections \
          --target-python-version 3.10 \
          --use-schema-description \
          --snake-case-field \
          --disable-timestamp \
          --enum-field-as-literal one \
          --use-double-quotes \
          --field-constraints \
          --allow-population-by-field-name \
          --strict-nullable \
          --use-title-as-name
  genereer-vera-referentiedata:
    desc: Genereer VERA referentiedata
    cmds:
      - python scripts/genereer_vera_referentiedata.py
