stelsel: zelfstandige_woonruimten
begindatum: 2024-01-01
stelselgroepen:
  oppervlakte_van_vertrekken:
    class_naam: OppervlakteVanVertrekken
    begindatum: 2024-01-01
    versies:
      - class_naam: OppervlakteVanVertrekken2024
        begindatum: 2024-01-01
  oppervlakte_van_overige_ruimten:
    class_naam: OppervlakteVanOverigeRuimten
    begindatum: 2024-01-01
    versies:
      - class_naam: OppervlakteVanOverigeRuimten2024
        begindatum: 2024-01-01
  # verwarming:
  #   class_naam: Verwarming
  #   begindatum: 2024-01-01
  #   versies:
  #     - class_naam: Verwarming2024
  #       begindatum: 2024-01-01
