stelsel: zelfstandige_woonruimten
begindatum: 2024-01-01
stelselgroepen:
  oppervlakte_van_vertrekken:
    module: oppervlakte_van_vertrekken
    class_naam: OppervlakteVanVertrekken
    begindatum: 2024-01-01
  oppervlakte_van_overige_ruimten:
    module: oppervlakte_van_overige_ruimten
    class_naam: OppervlakteVanOverigeRuimten
    begindatum: 2024-01-01
  verwarming:
    module: verwarming
    class_naam: Verwarming
    begindatum: 2024-01-01
  energieprestatie:
    module: energieprestatie
    class_naam: Energieprestatie
    begindatum: 2024-01-01
  sanitair:
    module: sanitair
    class_naam: Sanitair
    begindatum: 2024-01-01
  keuken:
    module: keuken
    class_naam: Keuken
    begindatum: 2024-01-01
  prive_buitenruimten:
    module: prive_buitenruimten
    class_naam: PriveBuitenruimten
    begindatum: 2024-01-01
  punten_voor_de_woz_waarde:
    module: punten_voor_de_woz_waarde
    class_naam: PuntenVoorDeWozWaarde
    begindatum: 2024-01-01
  renovatie:
    module: renovatie
    class_naam: Renovatie
    begindatum: 2024-01-01
    einddatum: 2024-06-30
  beschermd_monument_bmz:
    module: beschermd_monument_bmz
    class_naam: BeschermdMonumentBmz
    begindatum: 2024-01-01
    einddatum: 2024-06-30
  prijsopslag_monumenten_en_nieuwbouw:
    module: prijsopslag_monumenten_en_nieuwbouw
    class_naam: PrijsopslagMonumentenEnNieuwbouw
    begindatum: 2024-07-01
    uitvoeringsvolgorde: 100
