stelsel: zelfstandig
begindatum: 01-01-0001
einddatum: 31-12-9999
stelselgroepen:
  oppervlakte_van_vertrekken:
    class_naam: OppervlakteVanVertrekken
    begindatum: 01-01-0001
    einddatum: 31-12-9999
    versies:
      - class_naam: OppervlakteVanVertrekken2024
        begindatum: 01-01-2024
        einddatum: 31-12-9999

      - class_naam: OppervlakteVanVertrekken2023
        begindatum: 01-01-0001
        einddatum: 31-12-2023

  oppervlakte_van_overige_ruimten:
    class_naam: OppervlakteVanOverigeRuimten
    begindatum: 01-01-0001
    einddatum: 31-12-9999
    versies:
      - class_naam: OppervlakteVanOverigeRuimten2024
        begindatum: 01-01-0001
        einddatum: 31-12-9999
