stelsel: zelfstandig
begindatum: null
einddatum: 31-12-9999
stelselgroepen:
  oppervlakte_van_vertrekken:
    class_naam: OppervlakteVanVertrekken
    begindatum: null
    einddatum: 31-12-9999
    versies:
      - versie: OppervlakteVanVertrekken2024
        begindatum: null
        einddatum: 31-12-9999

      - versie: OppervlakteVanVertrekken2023
        begindatum: null
        einddatum: 31-12-2023

  oppervlakte_van_overige_ruimten:
    class_naam: OppervlakteVanOverigeRuimten
    begindatum: null
    einddatum: 31-12-9999
    versies:
      - versie: OppervlakteVanOverigeRuimten2024
        begindatum: null
        einddatum: 31-12-9999
